require("dotenv").config();
require("./config/database");
const Shrine = require("./models/shrine");

const shrines = [
  // ─── HOKKAIDO ───────────────────────────────────────────────────────────────
  {
    name: "Hokkaido Shrine",
    location: "Sapporo - Hokkaido, Japan",
    address: "474 Miyagaoka, Chuo-ku, Sapporo, Hokkaido 064-8505, Japan",
    country: "Japan",
    coordinates: { latitude: 43.0542, longitude: 141.3077 },
  },
  {
    name: "Hakodate Hachimangu",
    location: "Hakodate - Hokkaido, Japan",
    address: "Hakodate, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 41.7687, longitude: 140.7292 },
  },
  {
    name: "Hokkaido Gokoku Shrine",
    location: "Sapporo - Hokkaido, Japan",
    address: "Sapporo, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 43.056, longitude: 141.308 },
  },
  {
    name: "Hokkaido Tosho-gu",
    location: "Sapporo - Hokkaido, Japan",
    address: "Sapporo, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 43.065, longitude: 141.354 },
  },
  {
    name: "Sapporo Hachimangu",
    location: "Sapporo - Hokkaido, Japan",
    address: "Sapporo, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 43.065, longitude: 141.32 },
  },
  {
    name: "Tarumaezan Shrine",
    location: "Tomakomai - Hokkaido, Japan",
    address: "Tomakomai, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 42.6886, longitude: 141.3768 },
  },
  {
    name: "Asahikawa Shrine",
    location: "Asahikawa - Hokkaido, Japan",
    address: "Asahikawa, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 43.7710, longitude: 142.3649 },
  },
  {
    name: "Ebetsu Shrine",
    location: "Ebetsu - Hokkaido, Japan",
    address: "Ebetsu, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 43.1063, longitude: 141.5394 },
  },
  {
    name: "Obihiro Shrine",
    location: "Obihiro - Hokkaido, Japan",
    address: "Obihiro, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 42.9174, longitude: 143.1968 },
  },
  {
    name: "Ubagami Daijingu",
    location: "Haboro - Hokkaido, Japan",
    address: "Haboro, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 44.3626, longitude: 141.6973 },
  },
  {
    name: "Iwamizawa Shrine",
    location: "Iwamizawa - Hokkaido, Japan",
    address: "Iwamizawa, Hokkaido, Japan",
    country: "Japan",
    coordinates: { latitude: 43.195, longitude: 141.776 },
  },

  // ─── AOMORI ──────────────────────────────────────────────────────────────────
  {
    name: "Iwakiyama Shrine",
    location: "Hirosaki - Aomori, Japan",
    address: "Hirosaki, Aomori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 40.6608, longitude: 140.3133 },
  },
  {
    name: "Kabushima Shrine",
    location: "Hachinohe - Aomori, Japan",
    address: "Hachinohe, Aomori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 40.5083, longitude: 141.5328 },
  },
  {
    name: "Kushihiki Hachimangu",
    location: "Hachinohe - Aomori, Japan",
    address: "Hachinohe, Aomori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 40.5394, longitude: 141.4854 },
  },
  {
    name: "Hirosaki Tosho-gu",
    location: "Hirosaki - Aomori, Japan",
    address: "Hirosaki, Aomori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 40.6037, longitude: 140.4648 },
  },
  {
    name: "Takayama Inari Shrine",
    location: "Tsugaru - Aomori, Japan",
    address: "Tsugaru, Aomori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 40.8136, longitude: 140.3636 },
  },
  {
    name: "Saruka Shrine",
    location: "Aomori - Aomori, Japan",
    address: "Aomori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 40.82, longitude: 140.75 },
  },

  // ─── IWATE ───────────────────────────────────────────────────────────────────
  {
    name: "Komagata Shrine",
    location: "Miyako - Iwate, Japan",
    address: "Miyako, Iwate Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 39.6399, longitude: 141.9573 },
  },
  {
    name: "Morioka Hachimangu",
    location: "Morioka - Iwate, Japan",
    address: "Morioka, Iwate Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 39.7003, longitude: 141.1567 },
  },

  // ─── MIYAGI ──────────────────────────────────────────────────────────────────
  {
    name: "Aoba Shrine",
    location: "Sendai - Miyagi, Japan",
    address: "7-1 Aoba-cho, Aoba-ku, Sendai, Miyagi Prefecture 980-0916, Japan",
    country: "Japan",
    coordinates: { latitude: 38.2828, longitude: 140.8629 },
  },
  {
    name: "Osaki Hachimangu",
    location: "Sendai - Miyagi, Japan",
    address: "4-6-1 Hachiman, Aoba-ku, Sendai, Miyagi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.2722, longitude: 140.845 },
  },
  {
    name: "Sendai Tosho-gu",
    location: "Sendai - Miyagi, Japan",
    address: "Sendai, Miyagi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.268, longitude: 140.868 },
  },
  {
    name: "Shiogama Shrine",
    location: "Shiogama - Miyagi, Japan",
    address: "1-1 Ichimoriyama, Shiogama, Miyagi Prefecture 985-8510, Japan",
    country: "Japan",
    coordinates: { latitude: 38.3192, longitude: 141.0119 },
  },
  {
    name: "Takekoma Inari Shrine",
    location: "Iwanuma - Miyagi, Japan",
    address: "1-1 Inari-cho, Iwanuma, Miyagi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.105, longitude: 140.8623 },
  },
  {
    name: "Koganeyama Shrine",
    location: "Ishinomaki - Miyagi, Japan",
    address: "Ishinomaki, Miyagi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.3005, longitude: 141.5022 },
  },

  // ─── AKITA ───────────────────────────────────────────────────────────────────
  {
    name: "Koshio Shrine",
    location: "Akita - Akita, Japan",
    address: "Akita Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 39.716, longitude: 140.1023 },
  },
  {
    name: "Roken Shrine",
    location: "Akita - Akita, Japan",
    address: "Akita Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 39.72, longitude: 140.11 },
  },

  // ─── YAMAGATA ────────────────────────────────────────────────────────────────
  {
    name: "Chokaisaan Omomoimi Shrine",
    location: "Akumi District - Yamagata, Japan",
    address: "Akumi District, Yamagata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 39.0966, longitude: 140.0367 },
  },
  {
    name: "Dewa Shrine (Hagurosan)",
    location: "Tsuruoka - Yamagata, Japan",
    address: "Tsuruoka, Yamagata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.7135, longitude: 139.9762 },
  },
  {
    name: "Gassan Shrine",
    location: "Nishiokitama District - Yamagata, Japan",
    address: "Nishiokitama District, Yamagata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.5507, longitude: 140.0264 },
  },
  {
    name: "Yudonosan Shrine",
    location: "Tsuruoka - Yamagata, Japan",
    address: "Tsuruoka, Yamagata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.5701, longitude: 139.9629 },
  },
  {
    name: "Uesugi Shrine",
    location: "Yonezawa - Yamagata, Japan",
    address: "Yonezawa, Yamagata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.9224, longitude: 140.1148 },
  },
  {
    name: "Kumano Shrine (Yamagata)",
    location: "Higashiokitama District - Yamagata, Japan",
    address: "Higashiokitama District, Yamagata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.97, longitude: 140.21 },
  },

  // ─── FUKUSHIMA ───────────────────────────────────────────────────────────────
  {
    name: "Iino Hachimangu",
    location: "Fukushima - Fukushima, Japan",
    address: "Fukushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.749, longitude: 140.467 },
  },
  {
    name: "Isasumi Shrine",
    location: "Higashishirakawa District - Fukushima, Japan",
    address: "Higashishirakawa District, Fukushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.9899, longitude: 140.3812 },
  },
  {
    name: "Tsutsukowake Shrine",
    location: "Higashishirakawa District - Fukushima, Japan",
    address: "Higashishirakawa District, Fukushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.01, longitude: 140.39 },
  },
  {
    name: "Ryozen Shrine",
    location: "Fukushima - Fukushima, Japan",
    address: "Fukushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.75, longitude: 140.47 },
  },
  {
    name: "Okaburaya Shrine",
    location: "Fukushima - Fukushima, Japan",
    address: "Fukushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.756, longitude: 140.474 },
  },

  // ─── IBARAKI ─────────────────────────────────────────────────────────────────
  {
    name: "Kashima Shrine",
    location: "Kashima - Ibaraki, Japan",
    address: "2306-1 Kyuchu, Kashima, Ibaraki Prefecture 314-0031, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9689, longitude: 140.6314 },
  },
  {
    name: "Kasama Inari Shrine",
    location: "Kasama - Ibaraki, Japan",
    address: "1 Kasama, Kasama, Ibaraki Prefecture 309-1611, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3788, longitude: 140.2616 },
  },
  {
    name: "Tsukubasan Shrine",
    location: "Tsukuba - Ibaraki, Japan",
    address: "Tsukuba 1, Tsukuba, Ibaraki Prefecture 300-4352, Japan",
    country: "Japan",
    coordinates: { latitude: 36.2137, longitude: 140.1013 },
  },
  {
    name: "Oarai Isosaki Shrine",
    location: "Oarai - Ibaraki, Japan",
    address: "6890 Isohama-cho, Oarai-machi, Higashiibaraki-gun, Ibaraki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3159, longitude: 140.5874 },
  },
  {
    name: "Mito Tosho-gu",
    location: "Mito - Ibaraki, Japan",
    address: "Mito, Ibaraki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3701, longitude: 140.4775 },
  },
  {
    name: "Tokiwa Shrine",
    location: "Mito - Ibaraki, Japan",
    address: "Mito, Ibaraki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3756, longitude: 140.4739 },
  },

  // ─── TOCHIGI ─────────────────────────────────────────────────────────────────
  {
    name: "Nikko Tosho-gu",
    location: "Nikko - Tochigi, Japan",
    address: "2301 Sannai, Nikko, Tochigi Prefecture 321-1431, Japan",
    country: "Japan",
    coordinates: { latitude: 36.7581, longitude: 139.599 },
  },
  {
    name: "Futarasan Shrine",
    location: "Nikko - Tochigi, Japan",
    address: "Nikko, Tochigi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.7583, longitude: 139.5964 },
  },
  {
    name: "Utsunomiya Futarayama Shrine",
    location: "Utsunomiya - Tochigi, Japan",
    address: "Utsunomiya, Tochigi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.5561, longitude: 139.8833 },
  },
  {
    name: "Hoshinomiya Shrine",
    location: "Sano - Tochigi, Japan",
    address: "Sano, Tochigi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3157, longitude: 139.5789 },
  },

  // ─── GUNMA ───────────────────────────────────────────────────────────────────
  {
    name: "Haruna Shrine",
    location: "Takasaki - Gunma, Japan",
    address: "849 Harunasan-cho, Takasaki, Gunma Prefecture 370-3341, Japan",
    country: "Japan",
    coordinates: { latitude: 36.4585, longitude: 138.8522 },
  },
  {
    name: "Nukisaki Shrine",
    location: "Tomioka - Gunma, Japan",
    address: "Tomioka, Gunma Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.2573, longitude: 138.8898 },
  },
  {
    name: "Ikushina Shrine",
    location: "Gunma - Gunma, Japan",
    address: "Gunma Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.46, longitude: 139.06 },
  },
  {
    name: "Nakanotake Shrine",
    location: "Gunma - Gunma, Japan",
    address: "Gunma Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.55, longitude: 138.98 },
  },
  {
    name: "Maebashi Tosho-gu",
    location: "Maebashi - Gunma, Japan",
    address: "Maebashi, Gunma Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3895, longitude: 139.0634 },
  },
  {
    name: "Serada Tosho-gu",
    location: "Ora District - Gunma, Japan",
    address: "Ora District, Gunma Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.26, longitude: 139.44 },
  },

  // ─── SAITAMA ─────────────────────────────────────────────────────────────────
  {
    name: "Hikawa Shrine",
    location: "Omiya Ward, Saitama - Saitama, Japan",
    address: "1-407 Takahana-cho, Omiya-ku, Saitama, Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9167, longitude: 139.6294 },
  },
  {
    name: "Chichibu Shrine",
    location: "Chichibu - Saitama, Japan",
    address: "1-3 Banba-machi, Chichibu, Saitama Prefecture 368-0041, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9975, longitude: 139.0842 },
  },
  {
    name: "Mitsumine Shrine",
    location: "Chichibu - Saitama, Japan",
    address: "298-1 Mitsumine, Chichibu, Saitama Prefecture 369-1902, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9714, longitude: 138.9681 },
  },
  {
    name: "Washinomiya Shrine",
    location: "Kuki - Saitama, Japan",
    address: "Kuki, Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0999, longitude: 139.6549 },
  },
  {
    name: "Kanasana Shrine",
    location: "Kamikawa - Saitama, Japan",
    address: "Kamikawa, Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.1167, longitude: 139.0167 },
  },
  {
    name: "Koma Shrine",
    location: "Hidaka - Saitama, Japan",
    address: "Hidaka, Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.8785, longitude: 139.3373 },
  },
  {
    name: "Hatogamine Hachiman Shrine",
    location: "Saitama - Saitama, Japan",
    address: "Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.986, longitude: 139.631 },
  },
  {
    name: "Hikawa Shrine (Kawagoe)",
    location: "Kawagoe - Saitama, Japan",
    address: "Kawagoe, Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9236, longitude: 139.4844 },
  },
  {
    name: "Tokorozawa Shinmei Shrine",
    location: "Tokorozawa - Saitama, Japan",
    address: "Tokorozawa, Saitama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7996, longitude: 139.4686 },
  },

  // ─── CHIBA ───────────────────────────────────────────────────────────────────
  {
    name: "Katori Shrine",
    location: "Katori - Chiba, Japan",
    address: "1697 Katori, Katori, Chiba Prefecture 287-0017, Japan",
    country: "Japan",
    coordinates: { latitude: 35.8861, longitude: 140.5289 },
  },
  {
    name: "Awa Shrine",
    location: "Tateyama - Chiba, Japan",
    address: "Tateyama, Chiba Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9763, longitude: 139.8554 },
  },
  {
    name: "Chiba Shrine",
    location: "Chiba - Chiba, Japan",
    address: "Chiba, Chiba Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6073, longitude: 140.1223 },
  },
  {
    name: "Tamasaki Shrine",
    location: "Chosei District - Chiba, Japan",
    address: "Ichinomiya, Chosei District, Chiba Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3862, longitude: 140.3712 },
  },
  {
    name: "Susaki Shrine",
    location: "Tateyama - Chiba, Japan",
    address: "Tateyama, Chiba Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9706, longitude: 139.8547 },
  },
  {
    name: "Komikado Shrine",
    location: "Chiba - Chiba, Japan",
    address: "Chiba Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.584, longitude: 140.101 },
  },
  {
    name: "Tsutsumori Shrine",
    location: "Chiba - Chiba, Japan",
    address: "Chiba Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.62, longitude: 140.12 },
  },

  // ─── TOKYO ───────────────────────────────────────────────────────────────────
  {
    name: "Meiji Shrine",
    location: "Shibuya - Tokyo, Japan",
    address: "1-1 Kamizono-cho, Yoyogi, Shibuya, Tokyo 151-0053, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6761, longitude: 139.6992 },
  },
  {
    name: "Yasukuni Shrine",
    location: "Chiyoda - Tokyo, Japan",
    address: "3-1-1 Kudankita, Chiyoda, Tokyo 102-8246, Japan",
    country: "Japan",
    coordinates: { latitude: 35.694, longitude: 139.7427 },
  },
  {
    name: "Kanda Shrine",
    location: "Chiyoda - Tokyo, Japan",
    address: "2-16-2 Soto-Kanda, Chiyoda, Tokyo 101-0021, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7019, longitude: 139.7678 },
  },
  {
    name: "Hie Shrine",
    location: "Chiyoda - Tokyo, Japan",
    address: "2-10-5 Nagatacho, Chiyoda, Tokyo 100-0014, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6747, longitude: 139.7396 },
  },
  {
    name: "Nezu Shrine",
    location: "Bunkyo - Tokyo, Japan",
    address: "1 Chome-28-9 Nezu, Bunkyo, Tokyo 113-0031, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7203, longitude: 139.7608 },
  },
  {
    name: "Asakusa Shrine",
    location: "Taito - Tokyo, Japan",
    address: "2-3-1 Asakusa, Taito, Tokyo 111-0032, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7151, longitude: 139.7974 },
  },
  {
    name: "Yushima Tenmangu",
    location: "Bunkyo - Tokyo, Japan",
    address: "3 Chome-30-1 Yushima, Bunkyo, Tokyo 113-0034, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7078, longitude: 139.7683 },
  },
  {
    name: "Hanazono Shrine",
    location: "Shinjuku - Tokyo, Japan",
    address: "5-17-3 Shinjuku, Shinjuku, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6936, longitude: 139.7052 },
  },
  {
    name: "Tomioka Hachimangu",
    location: "Koto - Tokyo, Japan",
    address: "1-20-3 Tomioka, Koto, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6718, longitude: 139.7996 },
  },
  {
    name: "Oji Shrine",
    location: "Kita - Tokyo, Japan",
    address: "1 Chome-1-12 Ojihoncho, Kita, Tokyo 114-0022, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7533, longitude: 139.7359 },
  },
  {
    name: "Kameido Tenjin Shrine",
    location: "Koto - Tokyo, Japan",
    address: "3-6-1 Kameido, Koto, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.703, longitude: 139.8207 },
  },
  {
    name: "Suitengu (Tokyo)",
    location: "Chuo - Tokyo, Japan",
    address: "2-4-1 Suitengucho, Chuo, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6838, longitude: 139.7754 },
  },
  {
    name: "Atago Shrine (Tokyo)",
    location: "Minato - Tokyo, Japan",
    address: "1-5-3 Atago, Minato, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6656, longitude: 139.7494 },
  },
  {
    name: "Namiyoke Inari Shrine",
    location: "Chuo - Tokyo, Japan",
    address: "6-4-7 Tsukijima, Chuo, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6657, longitude: 139.7716 },
  },
  {
    name: "Nogi Shrine (Tokyo)",
    location: "Minato - Tokyo, Japan",
    address: "8-11-27 Akasaka, Minato, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6737, longitude: 139.7295 },
  },
  {
    name: "Togo Shrine",
    location: "Shibuya - Tokyo, Japan",
    address: "1-5-3 Jingumae, Shibuya, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6685, longitude: 139.7064 },
  },
  {
    name: "Tokyo Daijingu",
    location: "Chiyoda - Tokyo, Japan",
    address: "2-4-1 Fujimi, Chiyoda, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7017, longitude: 139.7456 },
  },
  {
    name: "Okunitama Shrine",
    location: "Fuchu - Tokyo, Japan",
    address: "3-1 Miyacho, Fuchu, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6697, longitude: 139.4787 },
  },
  {
    name: "Omiya Hachimangu (Tokyo)",
    location: "Suginami - Tokyo, Japan",
    address: "1-20-3 Omiya, Suginami, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6984, longitude: 139.6396 },
  },
  {
    name: "Shiba Tosho-gu",
    location: "Minato - Tokyo, Japan",
    address: "4-8-10 Shiba-koen, Minato, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6568, longitude: 139.7489 },
  },
  {
    name: "Ueno Tosho-gu",
    location: "Taito - Tokyo, Japan",
    address: "9-88 Uenokoen, Taito, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7148, longitude: 139.7742 },
  },
  {
    name: "Yabo Tenmanguo",
    location: "Kokubunji - Tokyo, Japan",
    address: "2-13-1 Nishimotocho, Kokubunji, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.7099, longitude: 139.4632 },
  },
  {
    name: "Kasai Shrine",
    location: "Edogawa - Tokyo, Japan",
    address: "2-22-2 Higashikasai, Edogawa, Tokyo, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6606, longitude: 139.8759 },
  },

  // ─── KANAGAWA ────────────────────────────────────────────────────────────────
  {
    name: "Tsurugaoka Hachimangu",
    location: "Kamakura - Kanagawa, Japan",
    address: "2-1-31 Yukinoshita, Kamakura, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3247, longitude: 139.5558 },
  },
  {
    name: "Enoshima Shrine",
    location: "Fujisawa - Kanagawa, Japan",
    address: "2-3-8 Enoshima, Fujisawa, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3006, longitude: 139.4797 },
  },
  {
    name: "Hakone Shrine",
    location: "Hakone - Kanagawa, Japan",
    address: "80-1 Hakone-machi, Ashigarashimo District, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.2039, longitude: 139.0256 },
  },
  {
    name: "Samukawa Shrine",
    location: "Koza District - Kanagawa, Japan",
    address: "3916 Miyayama, Samukawa-machi, Koza-gun, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3786, longitude: 139.3814 },
  },
  {
    name: "Kamakura-gu",
    location: "Kamakura - Kanagawa, Japan",
    address: "2-1-31 Nikaido, Kamakura, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3244, longitude: 139.5613 },
  },
  {
    name: "Egara Tenjin Shrine",
    location: "Kamakura - Kanagawa, Japan",
    address: "65 Nikaido, Kamakura, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3273, longitude: 139.5618 },
  },
  {
    name: "Iseyama Kotaijingu",
    location: "Nishi Ward, Yokohama - Kanagawa, Japan",
    address: "64 Miyazakicho, Nishi-ku, Yokohama, Kanagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4705, longitude: 139.6175 },
  },

  // ─── NIIGATA ─────────────────────────────────────────────────────────────────
  {
    name: "Yahiko Shrine",
    location: "Nishikanbara District - Niigata, Japan",
    address: "Yahiko, Nishikanbara District, Niigata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.7066, longitude: 138.8261 },
  },
  {
    name: "Kota Shrine (Niigata)",
    location: "Joetsu - Niigata, Japan",
    address: "Joetsu, Niigata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.1456, longitude: 138.2365 },
  },
  {
    name: "Amatsu Shrine",
    location: "Itoigawa - Niigata, Japan",
    address: "Itoigawa, Niigata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 37.0359, longitude: 137.8627 },
  },
  {
    name: "Watatsu Shrine",
    location: "Sado - Niigata, Japan",
    address: "Sado Island, Niigata Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 38.0569, longitude: 138.3699 },
  },

  // ─── TOYAMA ──────────────────────────────────────────────────────────────────
  {
    name: "Imizu Shrine",
    location: "Takaoka - Toyama, Japan",
    address: "Takaoka, Toyama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.7561, longitude: 137.0124 },
  },
  {
    name: "Keta Jinja (Toyama)",
    location: "Takaoka - Toyama, Japan",
    address: "Takaoka, Toyama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.7436, longitude: 137.0238 },
  },
  {
    name: "Takase Shrine",
    location: "Nanto - Toyama, Japan",
    address: "Nanto, Toyama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.5518, longitude: 136.9671 },
  },
  {
    name: "Oyama Shrine (Tateyama)",
    location: "Nakaniikawa District - Toyama, Japan",
    address: "Nakaniikawa District, Toyama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.5752, longitude: 137.6175 },
  },
  {
    name: "Toyama Gokoku Shrine",
    location: "Toyama - Toyama, Japan",
    address: "Toyama, Toyama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.6953, longitude: 137.2137 },
  },

  // ─── ISHIKAWA ────────────────────────────────────────────────────────────────
  {
    name: "Shirayama Hime Shrine",
    location: "Hakusan - Ishikawa, Japan",
    address: "105-1 Ni, Sannomiya-machi, Hakusan, Ishikawa Prefecture 920-2114, Japan",
    country: "Japan",
    coordinates: { latitude: 36.4349, longitude: 136.6361 },
  },
  {
    name: "Keta Taisha",
    location: "Hakui - Ishikawa, Japan",
    address: "Hakui, Ishikawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.926, longitude: 136.7675 },
  },
  {
    name: "Oyama Shrine (Kanazawa)",
    location: "Kanazawa - Ishikawa, Japan",
    address: "Kanazawa, Ishikawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.5664, longitude: 136.6553 },
  },
  {
    name: "Toyokuni Shrine (Kanazawa)",
    location: "Kanazawa - Ishikawa, Japan",
    address: "Kanazawa, Ishikawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.561, longitude: 136.659 },
  },

  // ─── FUKUI ───────────────────────────────────────────────────────────────────
  {
    name: "Kehi Shrine",
    location: "Tsuruga - Fukui, Japan",
    address: "11-68 Akebono-cho, Tsuruga, Fukui Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.655, longitude: 136.0747 },
  },
  {
    name: "Wakasahiko Shrine",
    location: "Obama - Fukui, Japan",
    address: "Obama, Fukui Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4979, longitude: 135.7387 },
  },
  {
    name: "Fujishima Shrine",
    location: "Fukui - Fukui, Japan",
    address: "Fukui, Fukui Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0743, longitude: 136.2273 },
  },
  {
    name: "Kanegasaki-gu",
    location: "Tsuruga - Fukui, Japan",
    address: "Tsuruga, Fukui Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6464, longitude: 136.0646 },
  },
  {
    name: "Heisenji Hakusan Shrine",
    location: "Katsuyama - Fukui, Japan",
    address: "Katsuyama, Fukui Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0696, longitude: 136.4985 },
  },

  // ─── YAMANASHI ───────────────────────────────────────────────────────────────
  {
    name: "Fujisan Hongu Sengen Taisha",
    location: "Fujinomiya - Shizuoka, Japan",
    address: "1-1 Miya-cho, Fujinomiya, Shizuoka Prefecture 418-0067, Japan",
    country: "Japan",
    coordinates: { latitude: 35.2275, longitude: 138.6103 },
  },
  {
    name: "Ichinomiya Asama Shrine (Fuefuki)",
    location: "Fuefuki - Yamanashi, Japan",
    address: "Fuefuki, Yamanashi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6495, longitude: 138.5968 },
  },
  {
    name: "Takeda Shrine",
    location: "Kofu - Yamanashi, Japan",
    address: "Kofu, Yamanashi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.6779, longitude: 138.5639 },
  },

  // ─── NAGANO ──────────────────────────────────────────────────────────────────
  {
    name: "Suwa Taisha (Kamisha Honmiya)",
    location: "Suwa - Nagano, Japan",
    address: "Suwa, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9981, longitude: 138.1194 },
  },
  {
    name: "Suwa Taisha (Kamisha Maemiya)",
    location: "Chino - Nagano, Japan",
    address: "Chino, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.9911, longitude: 138.1334 },
  },
  {
    name: "Suwa Taisha (Shimosha Harumiya)",
    location: "Shimosuwa - Nagano, Japan",
    address: "Shimosuwa, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0819, longitude: 138.0819 },
  },
  {
    name: "Suwa Taisha (Shimosha Akimiya)",
    location: "Shimosuwa - Nagano, Japan",
    address: "Shimosuwa, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0753, longitude: 138.0911 },
  },
  {
    name: "Togakushi Shrine",
    location: "Nagano - Nagano, Japan",
    address: "Togakushi, Nagano, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.7428, longitude: 138.0853 },
  },
  {
    name: "Hotaka Shrine",
    location: "Azumino - Nagano, Japan",
    address: "Hotaka, Azumino, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.3546, longitude: 137.8781 },
  },
  {
    name: "Ikushimatarushima Shrine",
    location: "Matsumoto - Nagano, Japan",
    address: "Matsumoto, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.2381, longitude: 137.9723 },
  },
  {
    name: "Nishina Shinmei Shrine",
    location: "Omachi - Nagano, Japan",
    address: "Omachi, Nagano Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.5019, longitude: 137.8497 },
  },

  // ─── GIFU ────────────────────────────────────────────────────────────────────
  {
    name: "Nangū Taisha",
    location: "Tarui, Fuwa District - Gifu, Japan",
    address: "1734-1 Miyashiromine, Tarui, Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.361, longitude: 136.5253 },
  },
  {
    name: "Minashi Shrine",
    location: "Takayama - Gifu, Japan",
    address: "Takayama, Gifu Prefecture 506-0071, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0853, longitude: 137.2519 },
  },
  {
    name: "Gifu Gokoku Shrine",
    location: "Gifu - Gifu, Japan",
    address: "Gifu, Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4331, longitude: 136.7653 },
  },
  {
    name: "Hida Gokoku Shrine",
    location: "Takayama - Gifu, Japan",
    address: "Takayama, Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.1427, longitude: 137.2527 },
  },
  {
    name: "Inaba Shrine",
    location: "Gifu - Gifu, Japan",
    address: "Gifu, Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4158, longitude: 136.7606 },
  },
  {
    name: "Yorō Shrine",
    location: "Yoro - Gifu, Japan",
    address: "Yoro, Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.2987, longitude: 136.5561 },
  },
  {
    name: "Kashimori Shrine",
    location: "Gifu - Gifu, Japan",
    address: "Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.44, longitude: 136.76 },
  },
  {
    name: "Keta Wakamiya Shrine",
    location: "Gifu - Gifu, Japan",
    address: "Gifu Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.41, longitude: 136.76 },
  },

  // ─── SHIZUOKA ────────────────────────────────────────────────────────────────
  {
    name: "Mishima Taisha",
    location: "Mishima - Shizuoka, Japan",
    address: "1-5 Omiya-cho, Mishima, Shizuoka Prefecture 411-0035, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1219, longitude: 138.9189 },
  },
  {
    name: "Shizuoka Sengen Shrine",
    location: "Shizuoka - Shizuoka, Japan",
    address: "Shizuoka, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9742, longitude: 138.3996 },
  },
  {
    name: "Kunozan Tosho-gu",
    location: "Shizuoka - Shizuoka, Japan",
    address: "Shizuoka, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9576, longitude: 138.4419 },
  },
  {
    name: "Akihasan Hongu Akiha Shrine",
    location: "Hamamatsu - Shizuoka, Japan",
    address: "Hamamatsu, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1258, longitude: 137.8296 },
  },
  {
    name: "Kotonomama Hachimangu",
    location: "Kakegawa - Shizuoka, Japan",
    address: "Kakegawa, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.7696, longitude: 138.0147 },
  },
  {
    name: "Izusan Shrine",
    location: "Atami - Shizuoka, Japan",
    address: "Atami, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1041, longitude: 139.0751 },
  },
  {
    name: "Iinoya-gu",
    location: "Hamamatsu - Shizuoka, Japan",
    address: "Hamamatsu, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8721, longitude: 137.6947 },
  },
  {
    name: "Yaizu Shrine",
    location: "Yaizu - Shizuoka, Japan",
    address: "Yaizu, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8682, longitude: 138.3246 },
  },
  {
    name: "Oguni Shrine",
    location: "Shuchi District - Shizuoka, Japan",
    address: "Shuchi District, Shizuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.724, longitude: 137.878 },
  },

  // ─── AICHI ───────────────────────────────────────────────────────────────────
  {
    name: "Atsuta Shrine",
    location: "Atsuta Ward, Nagoya - Aichi, Japan",
    address: "1-1-1 Jingu, Atsuta-ku, Nagoya, Aichi Prefecture 456-8585, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1275, longitude: 136.9083 },
  },
  {
    name: "Masumida Shrine",
    location: "Ichinomiya - Aichi, Japan",
    address: "2-1 Masumida 1-chome, Ichinomiya, Aichi Prefecture 491-0043, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3075, longitude: 136.8019 },
  },
  {
    name: "Tsushima Shrine",
    location: "Tsushima - Aichi, Japan",
    address: "Tsushima, Aichi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1783, longitude: 136.7186 },
  },
  {
    name: "Tagata Shrine",
    location: "Komaki - Aichi, Japan",
    address: "Komaki, Aichi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3197, longitude: 136.9233 },
  },
  {
    name: "Toga Shrine (Aichi)",
    location: "Toyokawa - Aichi, Japan",
    address: "Toyokawa, Aichi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8296, longitude: 137.3769 },
  },
  {
    name: "Owari Okunitama Shrine",
    location: "Inazawa - Aichi, Japan",
    address: "Inazawa, Aichi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.2578, longitude: 136.7807 },
  },
  {
    name: "Rokusho Shrine (Okazaki)",
    location: "Okazaki - Aichi, Japan",
    address: "Okazaki, Aichi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9581, longitude: 137.1753 },
  },

  // ─── MIE ─────────────────────────────────────────────────────────────────────
  {
    name: "Ise Grand Shrine (Naiku)",
    location: "Ise - Mie, Japan",
    address: "1 Ujitachicho, Ise, Mie Prefecture 516-0023, Japan",
    country: "Japan",
    coordinates: { latitude: 34.455, longitude: 136.7258 },
  },
  {
    name: "Ise Grand Shrine (Geku)",
    location: "Ise - Mie, Japan",
    address: "279 Toyokawa-cho, Ise, Mie Prefecture 516-0042, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4883, longitude: 136.7019 },
  },
  {
    name: "Tsubaki Grand Shrine",
    location: "Suzuka - Mie, Japan",
    address: "1871 Otabi, Yamamoto-cho, Suzuka, Mie Prefecture 519-0315, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9644, longitude: 136.4517 },
  },
  {
    name: "Tado Taisha",
    location: "Kuwana - Mie, Japan",
    address: "1681 Tado, Tado-cho, Kuwana, Mie Prefecture 511-0106, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1355, longitude: 136.6226 },
  },
  {
    name: "Aekuni Shrine",
    location: "Iga - Mie, Japan",
    address: "Iga, Mie Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.7685, longitude: 136.1297 },
  },
  {
    name: "Futami Okitama Shrine",
    location: "Ise - Mie, Japan",
    address: "Futami-cho, Ise, Mie Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4762, longitude: 136.7827 },
  },
  {
    name: "Kitabatake Shrine",
    location: "Tsu - Mie, Japan",
    address: "Tsu, Mie Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6485, longitude: 136.1833 },
  },
  {
    name: "Izawa-no-miya",
    location: "Shima - Mie, Japan",
    address: "Shima, Mie Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.3352, longitude: 136.8288 },
  },

  // ─── SHIGA ───────────────────────────────────────────────────────────────────
  {
    name: "Hiyoshi Taisha",
    location: "Otsu - Shiga, Japan",
    address: "Otsu, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0734, longitude: 135.865 },
  },
  {
    name: "Omi Shrine",
    location: "Otsu - Shiga, Japan",
    address: "1-1 Jingu-cho, Otsu, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0324, longitude: 135.8512 },
  },
  {
    name: "Taga-taisha",
    location: "Inukami District - Shiga, Japan",
    address: "604 Taga, Inukami-gun, Shiga Prefecture 522-0341, Japan",
    country: "Japan",
    coordinates: { latitude: 35.2242, longitude: 136.2906 },
  },
  {
    name: "Takebe Taisha",
    location: "Otsu - Shiga, Japan",
    address: "Otsu, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0004, longitude: 135.9081 },
  },
  {
    name: "Tsukubusuma Shrine",
    location: "Nagahama - Shiga, Japan",
    address: "Nagahama, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4577, longitude: 136.1058 },
  },
  {
    name: "Mikami Shrine",
    location: "Yasu - Shiga, Japan",
    address: "Yasu, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0437, longitude: 136.0173 },
  },
  {
    name: "Shirahige Shrine",
    location: "Takashima - Shiga, Japan",
    address: "Takashima, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3982, longitude: 136.0091 },
  },
  {
    name: "Himure Hachimangu",
    location: "Omihachiman - Shiga, Japan",
    address: "Omihachiman, Shiga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1283, longitude: 136.0977 },
  },

  // ─── KYOTO ───────────────────────────────────────────────────────────────────
  {
    name: "Fushimi Inari Taisha",
    location: "Fushimi Ward - Kyoto, Japan",
    address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto 612-0882, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9672, longitude: 135.7728 },
  },
  {
    name: "Kamigamo Shrine",
    location: "Kita Ward - Kyoto, Japan",
    address: "339 Kamigamomotoyama, Kita-ku, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0603, longitude: 135.7528 },
  },
  {
    name: "Shimogamo Shrine",
    location: "Sakyo Ward - Kyoto, Japan",
    address: "59 Shimogamo Izumigawa-cho, Sakyo-ku, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0389, longitude: 135.7725 },
  },
  {
    name: "Heian Shrine",
    location: "Sakyo Ward - Kyoto, Japan",
    address: "97 Okazaki-Nishi-tenno-cho, Sakyo-ku, Kyoto, Kyoto Prefecture 606-8341, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0167, longitude: 135.7822 },
  },
  {
    name: "Kitano Tenmangu",
    location: "Kamigyo Ward - Kyoto, Japan",
    address: "Hakuraku-cho, Kamigyo-ku, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0311, longitude: 135.7353 },
  },
  {
    name: "Yasaka Shrine",
    location: "Higashiyama Ward - Kyoto, Japan",
    address: "625 Gionmachi Kitagawa, Higashiyama Ward, Kyoto 605-0073, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0036, longitude: 135.7786 },
  },
  {
    name: "Matsunoo Shrine",
    location: "Nishikyo Ward - Kyoto, Japan",
    address: "3 Arashiyamamiya-cho, Nishikyo-ku, Kyoto, Kyoto Prefecture 616-0024, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0003, longitude: 135.6853 },
  },
  {
    name: "Iwashimizu Hachimangu",
    location: "Yawata - Kyoto, Japan",
    address: "Yawata, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8797, longitude: 135.7 },
  },
  {
    name: "Ujigami Shrine",
    location: "Uji - Kyoto, Japan",
    address: "59 Ujiyamada, Uji, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8919, longitude: 135.8114 },
  },
  {
    name: "Kono Shrine",
    location: "Miyazu - Kyoto, Japan",
    address: "430 Ogaki, Miyazu, Kyoto Prefecture 629-2242, Japan",
    country: "Japan",
    coordinates: { latitude: 35.5828, longitude: 135.1967 },
  },
  {
    name: "Izumo-daijingu (Kameoka)",
    location: "Kameoka - Kyoto, Japan",
    address: "Chitose-cho, Kameoka, Kyoto Prefecture 621-0002, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0594, longitude: 135.5784 },
  },
  {
    name: "Tsukiyomi Shrine (Kyoto)",
    location: "Kyoto - Kyoto, Japan",
    address: "Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.97, longitude: 135.77 },
  },
  {
    name: "Imamiya Shrine",
    location: "Kita Ward - Kyoto, Japan",
    address: "21 Imamiya-cho, Murasakino Kita-ku, Kyoto, Kyoto Prefecture 603-8231, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0458, longitude: 135.7421 },
  },
  {
    name: "Yoshida Shrine",
    location: "Sakyo Ward - Kyoto, Japan",
    address: "Sakyo Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0264, longitude: 135.7833 },
  },
  {
    name: "Hirano Shrine",
    location: "Kita Ward - Kyoto, Japan",
    address: "Kita Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0369, longitude: 135.7322 },
  },
  {
    name: "Kibune Shrine",
    location: "Sakyo Ward - Kyoto, Japan",
    address: "Kibune, Sakyo Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1226, longitude: 135.7582 },
  },
  {
    name: "Goo Shrine",
    location: "Kamigyo Ward - Kyoto, Japan",
    address: "Kamigyo Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0261, longitude: 135.7589 },
  },
  {
    name: "Shiramine Jingu",
    location: "Kamigyo Ward - Kyoto, Japan",
    address: "Kamigyo Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0258, longitude: 135.748 },
  },
  {
    name: "Kenkun Shrine",
    location: "Kita Ward - Kyoto, Japan",
    address: "Kita Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0394, longitude: 135.7383 },
  },
  {
    name: "Toyokuni Shrine (Kyoto)",
    location: "Higashiyama Ward - Kyoto, Japan",
    address: "Higashiyama Ward, Kyoto, Kyoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.9969, longitude: 135.7752 },
  },

  // ─── OSAKA ───────────────────────────────────────────────────────────────────
  {
    name: "Sumiyoshi Taisha",
    location: "Sumiyoshi Ward, Osaka - Osaka, Japan",
    address: "9-89 Sumiyoshi 2-chome, Sumiyoshi-ku, Osaka, Osaka Prefecture 558-0045, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6128, longitude: 135.493 },
  },
  {
    name: "Osaka Tenmangu",
    location: "Kita Ward, Osaka - Osaka, Japan",
    address: "Kita Ward, Osaka, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6943, longitude: 135.509 },
  },
  {
    name: "Otori Taisha",
    location: "Naka Ward, Sakai - Osaka, Japan",
    address: "Sakai, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5582, longitude: 135.4748 },
  },
  {
    name: "Hiraoka Shrine",
    location: "Higashiosaka - Osaka, Japan",
    address: "Higashiosaka, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6543, longitude: 135.6673 },
  },
  {
    name: "Minase Shrine",
    location: "Shimamoto - Osaka, Japan",
    address: "Shimamoto, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8849, longitude: 135.673 },
  },
  {
    name: "Imamiya Ebisu Shrine",
    location: "Naniwa Ward, Osaka - Osaka, Japan",
    address: "Naniwa Ward, Osaka, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6695, longitude: 135.5046 },
  },
  {
    name: "Shijonaute Shrine",
    location: "Shijonaute - Osaka, Japan",
    address: "Shijonaute, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.7268, longitude: 135.6296 },
  },
  {
    name: "Sakurai Shrine (Sakai)",
    location: "Sakai - Osaka, Japan",
    address: "Sakai, Osaka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5648, longitude: 135.4893 },
  },

  // ─── HYOGO ───────────────────────────────────────────────────────────────────
  {
    name: "Ikuta Shrine",
    location: "Chuo Ward, Kobe - Hyogo, Japan",
    address: "1-2-1 Shimoyamate-dori, Chuo-ku, Kobe, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.695, longitude: 135.1906 },
  },
  {
    name: "Hirota Shrine",
    location: "Nishinomiya - Hyogo, Japan",
    address: "7-7 Taisha-cho, Nishinomiya, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.753, longitude: 135.34 },
  },
  {
    name: "Nagata Shrine",
    location: "Nagata Ward, Kobe - Hyogo, Japan",
    address: "Nagata Ward, Kobe, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6762, longitude: 135.1468 },
  },
  {
    name: "Nishinomiya Shrine",
    location: "Nishinomiya - Hyogo, Japan",
    address: "Nishinomiya, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.7294, longitude: 135.3413 },
  },
  {
    name: "Izushi Shrine",
    location: "Toyooka - Hyogo, Japan",
    address: "Toyooka, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4745, longitude: 134.8477 },
  },
  {
    name: "Izanagi Shrine",
    location: "Awaji - Hyogo, Japan",
    address: "Awaji, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4744, longitude: 134.8609 },
  },
  {
    name: "Minatogawa Shrine",
    location: "Chuo Ward, Kobe - Hyogo, Japan",
    address: "Chuo Ward, Kobe, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6765, longitude: 135.1798 },
  },
  {
    name: "Iwa Shrine",
    location: "Shiso - Hyogo, Japan",
    address: "Shiso, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.0019, longitude: 134.5356 },
  },
  {
    name: "Tada Shrine",
    location: "Kawanishi - Hyogo, Japan",
    address: "Kawanishi, Hyogo Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.8294, longitude: 135.4077 },
  },

  // ─── NARA ────────────────────────────────────────────────────────────────────
  {
    name: "Kasuga Taisha",
    location: "Nara - Nara, Japan",
    address: "160 Kasugano-cho, Nara, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6814, longitude: 135.8483 },
  },
  {
    name: "Omiwa Shrine",
    location: "Sakurai - Nara, Japan",
    address: "1422 Miwa, Sakurai, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5289, longitude: 135.8528 },
  },
  {
    name: "Kashihara Shrine",
    location: "Kashihara - Nara, Japan",
    address: "934 Kume-cho, Kashihara, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4884, longitude: 135.7865 },
  },
  {
    name: "Isonokami Shrine",
    location: "Tenri - Nara, Japan",
    address: "384 Furu-cho, Tenri, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5981, longitude: 135.8525 },
  },
  {
    name: "Tanzan Shrine",
    location: "Sakurai - Nara, Japan",
    address: "319 Tonomine, Sakurai, Nara Prefecture 633-0032, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4658, longitude: 135.8617 },
  },
  {
    name: "Tamukeyama Hachimangu",
    location: "Nara - Nara, Japan",
    address: "Nara, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6897, longitude: 135.8434 },
  },
  {
    name: "Yoshino Mikumari Shrine",
    location: "Yoshino - Nara, Japan",
    address: "Yoshino, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.3598, longitude: 135.857 },
  },
  {
    name: "Uda Mikumari Shrine",
    location: "Uda - Nara, Japan",
    address: "244-3 Utano-ken, Uda, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4747, longitude: 135.9706 },
  },
  {
    name: "Tatsuta Taisha",
    location: "Sangou - Nara, Japan",
    address: "Sangou, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5841, longitude: 135.7298 },
  },
  {
    name: "Hirose Shrine",
    location: "Katsuragi - Nara, Japan",
    address: "Katsuragi, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5849, longitude: 135.727 },
  },
  {
    name: "Ikoma Shrine",
    location: "Ikoma - Nara, Japan",
    address: "Ikoma, Nara Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6899, longitude: 135.7003 },
  },

  // ─── WAKAYAMA ────────────────────────────────────────────────────────────────
  {
    name: "Kumano Hongu Taisha",
    location: "Tanabe - Wakayama, Japan",
    address: "1110 Hongucho Hongu, Tanabe, Wakayama Prefecture 647-1731, Japan",
    country: "Japan",
    coordinates: { latitude: 33.84, longitude: 135.7739 },
  },
  {
    name: "Kumano Nachi Taisha",
    location: "Nachikatsuura - Wakayama, Japan",
    address: "Nachikatsuura, Higashimuro District, Wakayama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.6686, longitude: 135.8906 },
  },
  {
    name: "Kumano Hayatama Taisha",
    location: "Shingu - Wakayama, Japan",
    address: "Shingu, Wakayama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.732, longitude: 135.9837 },
  },
  {
    name: "Niutsuhime Shrine",
    location: "Katsuragi - Wakayama, Japan",
    address: "230 Kami-amano, Katsuragi-cho, Ito-gun, Wakayama Prefecture 649-7141, Japan",
    country: "Japan",
    coordinates: { latitude: 34.2627, longitude: 135.5195 },
  },
  {
    name: "Hinokuma Shrine",
    location: "Wakayama - Wakayama, Japan",
    address: "Wakayama, Wakayama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.1945, longitude: 135.1889 },
  },
  {
    name: "Itakiso Shrine",
    location: "Wakayama - Wakayama, Japan",
    address: "Wakayama, Wakayama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.1948, longitude: 135.189 },
  },

  // ─── TOTTORI ─────────────────────────────────────────────────────────────────
  {
    name: "Ube Shrine",
    location: "Tottori - Tottori, Japan",
    address: "Tottori, Tottori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.5076, longitude: 134.2346 },
  },
  {
    name: "Shitori Shrine",
    location: "Tohaku District - Tottori, Japan",
    address: "Tohaku District, Tottori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.5254, longitude: 133.7876 },
  },
  {
    name: "Ogamiyama Shrine",
    location: "Hoki - Tottori, Japan",
    address: "Hoki, Tottori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3498, longitude: 133.4817 },
  },
  {
    name: "Hakuto Shrine",
    location: "Tottori - Tottori, Japan",
    address: "Tottori, Tottori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.5486, longitude: 134.0765 },
  },
  {
    name: "Nawa Shrine",
    location: "Hoki - Tottori, Japan",
    address: "Hoki, Tottori Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3513, longitude: 133.4827 },
  },

  // ─── SHIMANE ─────────────────────────────────────────────────────────────────
  {
    name: "Izumo Taisha",
    location: "Izumo - Shimane, Japan",
    address: "195 Kitsukihigashi, Taisha-machi, Izumo, Shimane Prefecture 699-0701, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4019, longitude: 132.6856 },
  },
  {
    name: "Suda Shrine (Shimane)",
    location: "Matsue - Shimane, Japan",
    address: "Matsue, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4735, longitude: 133.0577 },
  },
  {
    name: "Kamosu Shrine",
    location: "Matsue - Shimane, Japan",
    address: "Matsue, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4251, longitude: 133.0851 },
  },
  {
    name: "Hinomisaki Shrine",
    location: "Izumo - Shimane, Japan",
    address: "Izumo, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4332, longitude: 132.6264 },
  },
  {
    name: "Miho Shrine",
    location: "Matsue - Shimane, Japan",
    address: "Matsue, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.5366, longitude: 133.2342 },
  },
  {
    name: "Sada Shrine",
    location: "Matsue - Shimane, Japan",
    address: "Matsue, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.5391, longitude: 132.9931 },
  },
  {
    name: "Yaegaki Shrine",
    location: "Matsue - Shimane, Japan",
    address: "Matsue, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.4115, longitude: 133.0601 },
  },
  {
    name: "Kumano Taisha (Shimane)",
    location: "Matsue - Shimane, Japan",
    address: "Matsue, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.3962, longitude: 133.0855 },
  },
  {
    name: "Mononobe Shrine",
    location: "Oda - Shimane, Japan",
    address: "Oda, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1892, longitude: 132.5015 },
  },
  {
    name: "Susa Shrine",
    location: "Unnan - Shimane, Japan",
    address: "Unnan, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1487, longitude: 132.8523 },
  },
  {
    name: "Taikodani Inari Shrine",
    location: "Tsuwano - Shimane, Japan",
    address: "Tsuwano, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4686, longitude: 131.775 },
  },
  {
    name: "Mizuwakasu Shrine",
    location: "Oki District - Shimane, Japan",
    address: "Oki Islands, Shimane Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 36.0962, longitude: 133.1882 },
  },

  // ─── OKAYAMA ─────────────────────────────────────────────────────────────────
  {
    name: "Kibitsu Shrine (Bitchu)",
    location: "Okayama - Okayama, Japan",
    address: "931 Kibitsu, Kita-ku, Okayama, Okayama Prefecture 701-1341, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6707, longitude: 133.8506 },
  },
  {
    name: "Kibitsuhiko Shrine",
    location: "Okayama - Okayama, Japan",
    address: "1043 Ichinomiya, Kita-ku, Okayama, Okayama Prefecture 701-1211, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6768, longitude: 133.8639 },
  },
  {
    name: "Nakayama Shrine (Tsuyama)",
    location: "Tsuyama - Okayama, Japan",
    address: "695 Ichinomiya, Tsuyama, Okayama Prefecture 708-0815, Japan",
    country: "Japan",
    coordinates: { latitude: 35.1002, longitude: 133.9946 },
  },
  {
    name: "Saijo Inari",
    location: "Okayama - Okayama, Japan",
    address: "Okayama, Okayama Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.6516, longitude: 133.9188 },
  },

  // ─── HIROSHIMA ───────────────────────────────────────────────────────────────
  {
    name: "Itsukushima Shrine",
    location: "Hatsukaichi - Hiroshima, Japan",
    address: "1-1 Miyajima-cho, Hatsukaichi, Hiroshima Prefecture 739-0588, Japan",
    country: "Japan",
    coordinates: { latitude: 34.2958, longitude: 132.3197 },
  },
  {
    name: "Hiroshima Gokoku Shrine",
    location: "Naka Ward, Hiroshima - Hiroshima, Japan",
    address: "Naka Ward, Hiroshima, Hiroshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.3955, longitude: 132.4593 },
  },
  {
    name: "Kibitsu Shrine (Bingo)",
    location: "Fukuyama - Hiroshima, Japan",
    address: "Fukuyama, Hiroshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4826, longitude: 133.3756 },
  },
  {
    name: "Fukuyama Hachimangu",
    location: "Fukuyama - Hiroshima, Japan",
    address: "Fukuyama, Hiroshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4881, longitude: 133.3633 },
  },
  {
    name: "Nunakuma Shrine",
    location: "Fukuyama - Hiroshima, Japan",
    address: "Fukuyama, Hiroshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4634, longitude: 133.3543 },
  },
  {
    name: "Hayatani Shrine",
    location: "Hiroshima - Hiroshima, Japan",
    address: "Hiroshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.5219, longitude: 132.6418 },
  },
  {
    name: "Hiroshima Tosho-gu",
    location: "Hiroshima - Hiroshima, Japan",
    address: "Hiroshima, Hiroshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.3892, longitude: 132.4538 },
  },

  // ─── YAMAGUCHI ───────────────────────────────────────────────────────────────
  {
    name: "Akama Shrine",
    location: "Shimonoseki - Yamaguchi, Japan",
    address: "4-1 Amidaiji-cho, Shimonoseki, Yamaguchi Prefecture 750-0003, Japan",
    country: "Japan",
    coordinates: { latitude: 33.9597, longitude: 130.9485 },
  },
  {
    name: "Sumiyoshi Shrine (Shimonoseki)",
    location: "Shimonoseki - Yamaguchi, Japan",
    address: "Shimonoseki, Yamaguchi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.9538, longitude: 130.9339 },
  },
  {
    name: "Hofu Tenmangu",
    location: "Hofu - Yamaguchi, Japan",
    address: "Hofu, Yamaguchi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.0474, longitude: 131.5622 },
  },
  {
    name: "Kameyama Hachimangu",
    location: "Shimonoseki - Yamaguchi, Japan",
    address: "Shimonoseki, Yamaguchi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.965, longitude: 130.963 },
  },
  {
    name: "Tamanooya Shrine",
    location: "Hofu - Yamaguchi, Japan",
    address: "Hofu, Yamaguchi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.0501, longitude: 131.5625 },
  },
  {
    name: "Iminomiya Shrine",
    location: "Shimonoseki - Yamaguchi, Japan",
    address: "Shimonoseki, Yamaguchi Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.9502, longitude: 130.9298 },
  },

  // ─── TOKUSHIMA ───────────────────────────────────────────────────────────────
  {
    name: "Oasahiko Shrine",
    location: "Naruto - Tokushima, Japan",
    address: "Naruto, Tokushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.2001, longitude: 134.5753 },
  },
  {
    name: "Ichinomiya Shrine (Tokushima)",
    location: "Tokushima - Tokushima, Japan",
    address: "Tokushima, Tokushima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.0762, longitude: 134.5461 },
  },

  // ─── KAGAWA ──────────────────────────────────────────────────────────────────
  {
    name: "Kotohira-gu",
    location: "Kotohira - Kagawa, Japan",
    address: "Kotohira, Kagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.1842, longitude: 133.8097 },
  },
  {
    name: "Tamura Shrine",
    location: "Takamatsu - Kagawa, Japan",
    address: "Takamatsu, Kagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.3498, longitude: 134.0461 },
  },
  {
    name: "Kandani Shrine",
    location: "Sakaide - Kagawa, Japan",
    address: "Sakaide, Kagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.3048, longitude: 133.8467 },
  },
  {
    name: "Kotohiki Hachimangu",
    location: "Kanonji - Kagawa, Japan",
    address: "Kanonji, Kagawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.1325, longitude: 133.6649 },
  },

  // ─── EHIME ───────────────────────────────────────────────────────────────────
  {
    name: "Oyamazumi Shrine",
    location: "Imabari - Ehime, Japan",
    address: "Imabari, Ehime Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.2572, longitude: 133.0049 },
  },
  {
    name: "Isaniwa Shrine",
    location: "Matsuyama - Ehime, Japan",
    address: "Matsuyama, Ehime Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.8506, longitude: 132.7892 },
  },

  // ─── KOCHI ───────────────────────────────────────────────────────────────────
  {
    name: "Tosa Shrine",
    location: "Kochi - Kochi, Japan",
    address: "16-1 Ikkushinane 2-chome, Kochi, Kochi Prefecture 781-8131, Japan",
    country: "Japan",
    coordinates: { latitude: 33.5926, longitude: 133.577 },
  },

  // ─── FUKUOKA ─────────────────────────────────────────────────────────────────
  {
    name: "Dazaifu Tenmanguo",
    location: "Dazaifu - Fukuoka, Japan",
    address: "4-7-1 Saifu, Dazaifu, Fukuoka Prefecture 818-0195, Japan",
    country: "Japan",
    coordinates: { latitude: 33.5214, longitude: 130.535 },
  },
  {
    name: "Munakata Taisha (Hetsu-gu)",
    location: "Munakata - Fukuoka, Japan",
    address: "2331 Tashima, Munakata, Fukuoka Prefecture 811-3505, Japan",
    country: "Japan",
    coordinates: { latitude: 33.8314, longitude: 130.5139 },
  },
  {
    name: "Munakata Taisha (Nakatsu-gu)",
    location: "Munakata - Fukuoka, Japan",
    address: "1811 Nii Oshima, Munakata, Fukuoka Prefecture 811-3701, Japan",
    country: "Japan",
    coordinates: { latitude: 33.8814, longitude: 130.4158 },
  },
  {
    name: "Hakozaki Shrine",
    location: "Higashi Ward, Fukuoka - Fukuoka, Japan",
    address: "Fukuoka, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.6144, longitude: 130.4233 },
  },
  {
    name: "Hikosan Jingu",
    location: "Soeda, Tagawa District - Fukuoka, Japan",
    address: "1 Hiko-san, Soeda, Tagawa District, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.4779, longitude: 130.9262 },
  },
  {
    name: "Miyajidake Shrine",
    location: "Fukutsu - Fukuoka, Japan",
    address: "7-1 Miyaji Motomachi, Fukutsu, Fukuoka Prefecture 811-3309, Japan",
    country: "Japan",
    coordinates: { latitude: 33.7797, longitude: 130.4861 },
  },
  {
    name: "Shikaumi Shrine",
    location: "Higashi Ward, Fukuoka - Fukuoka, Japan",
    address: "Fukuoka, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.6571, longitude: 130.4087 },
  },
  {
    name: "Sumiyoshi Shrine (Fukuoka)",
    location: "Hakata Ward, Fukuoka - Fukuoka, Japan",
    address: "3-1-51 Sumiyoshi, Hakata-ku, Fukuoka, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.5859, longitude: 130.4137 },
  },
  {
    name: "Kora Taisha",
    location: "Kurume - Fukuoka, Japan",
    address: "Kurume, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.2804, longitude: 130.5255 },
  },
  {
    name: "Kamado Shrine",
    location: "Dazaifu - Fukuoka, Japan",
    address: "Dazaifu, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.5173, longitude: 130.5428 },
  },
  {
    name: "Kurume Suitengu",
    location: "Kurume - Fukuoka, Japan",
    address: "Kurume, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.3175, longitude: 130.5161 },
  },
  {
    name: "Mekari Shrine",
    location: "Kitakyushu - Fukuoka, Japan",
    address: "Kitakyushu, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.9491, longitude: 130.9556 },
  },
  {
    name: "Umi Hachimangu",
    location: "Kasuya District - Fukuoka, Japan",
    address: "Kasuya District, Fukuoka Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.5929, longitude: 130.5157 },
  },

  // ─── SAGA ─────────────────────────────────────────────────────────────────────
  {
    name: "Yutoku Inari Shrine",
    location: "Kashima - Saga, Japan",
    address: "Kashima, Saga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.0736, longitude: 130.1083 },
  },
  {
    name: "Chiriku Hachimangu",
    location: "Miyaki - Saga, Japan",
    address: "Miyaki, Saga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.3673, longitude: 130.4754 },
  },
  {
    name: "Araho Shrine",
    location: "Saga - Saga, Japan",
    address: "Saga, Saga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.2614, longitude: 130.3001 },
  },
  {
    name: "Tozan Shrine",
    location: "Imari - Saga, Japan",
    address: "Imari, Saga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.2739, longitude: 129.8816 },
  },
  {
    name: "Kagami Shrine",
    location: "Saga - Saga, Japan",
    address: "Saga Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.25, longitude: 130.3 },
  },

  // ─── NAGASAKI ────────────────────────────────────────────────────────────────
  {
    name: "Suwa Shrine (Nagasaki)",
    location: "Nagasaki - Nagasaki, Japan",
    address: "Nagasaki, Nagasaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.7544, longitude: 129.8817 },
  },
  {
    name: "Sanno Shrine",
    location: "Nagasaki - Nagasaki, Japan",
    address: "Nagasaki, Nagasaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.7521, longitude: 129.8852 },
  },
  {
    name: "Nagasaki Gokoku Shrine",
    location: "Nagasaki - Nagasaki, Japan",
    address: "Nagasaki, Nagasaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.759, longitude: 129.891 },
  },
  {
    name: "Kaijin Shrine",
    location: "Tsushima - Nagasaki, Japan",
    address: "Tsushima, Nagasaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 34.4152, longitude: 129.2967 },
  },
  {
    name: "Sumiyoshi Shrine (Iki)",
    location: "Iki - Nagasaki, Japan",
    address: "Iki, Nagasaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.7498, longitude: 129.6892 },
  },

  // ─── KUMAMOTO ────────────────────────────────────────────────────────────────
  {
    name: "Aso Shrine",
    location: "Aso - Kumamoto, Japan",
    address: "3083-1 Ichinomiya-machi Miyaji, Aso, Kumamoto Prefecture 869-2612, Japan",
    country: "Japan",
    coordinates: { latitude: 32.9478, longitude: 131.116 },
  },
  {
    name: "Aoi Aso Shrine",
    location: "Hitoyoshi - Kumamoto, Japan",
    address: "Hitoyoshi, Kumamoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.2156, longitude: 130.7525 },
  },
  {
    name: "Fujisaki Hachimangu",
    location: "Kumamoto - Kumamoto, Japan",
    address: "Kumamoto, Kumamoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.8042, longitude: 130.7025 },
  },
  {
    name: "Kato Shrine",
    location: "Kumamoto - Kumamoto, Japan",
    address: "Kumamoto, Kumamoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.8091, longitude: 130.7063 },
  },
  {
    name: "Kengun Shrine",
    location: "Kumamoto - Kumamoto, Japan",
    address: "Kumamoto, Kumamoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.8096, longitude: 130.7481 },
  },
  {
    name: "Kikuchi Shrine",
    location: "Kikuchi - Kumamoto, Japan",
    address: "Kikuchi, Kumamoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.9822, longitude: 130.8146 },
  },
  {
    name: "Yatsushiro-gu",
    location: "Yatsushiro - Kumamoto, Japan",
    address: "Yatsushiro, Kumamoto Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.5052, longitude: 130.6086 },
  },

  // ─── OITA ────────────────────────────────────────────────────────────────────
  {
    name: "Usa Shrine",
    location: "Usa - Oita, Japan",
    address: "2859 Oaza Minamiusa, Usa, Oita Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.5261, longitude: 131.3747 },
  },
  {
    name: "Yusuhara Hachimangu",
    location: "Oita - Oita, Japan",
    address: "Oita, Oita Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.2388, longitude: 131.6126 },
  },
  {
    name: "Sasamuta Shrine",
    location: "Oita - Oita, Japan",
    address: "Oita, Oita Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 33.2338, longitude: 131.6113 },
  },

  // ─── MIYAZAKI ────────────────────────────────────────────────────────────────
  {
    name: "Miyazaki Jingu",
    location: "Miyazaki - Miyazaki, Japan",
    address: "2-4-1 Jingu, Miyazaki, Miyazaki Prefecture 880-0053, Japan",
    country: "Japan",
    coordinates: { latitude: 31.9386, longitude: 131.4233 },
  },
  {
    name: "Aoshima Shrine",
    location: "Miyazaki - Miyazaki, Japan",
    address: "2-13-1 Aoshima, Miyazaki, Miyazaki Prefecture 889-2162, Japan",
    country: "Japan",
    coordinates: { latitude: 31.8047, longitude: 131.4747 },
  },
  {
    name: "Takachiho Shrine",
    location: "Nishiusuki District - Miyazaki, Japan",
    address: "1037 Mitai, Takachiho, Nishiusuki District, Miyazaki Prefecture 882-1101, Japan",
    country: "Japan",
    coordinates: { latitude: 32.7067, longitude: 131.3017 },
  },
  {
    name: "Amanoiwato Shrine",
    location: "Nishiusuki District - Miyazaki, Japan",
    address: "Takachiho, Nishiusuki District, Miyazaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.7194, longitude: 131.2764 },
  },
  {
    name: "Tsuno Shrine",
    location: "Tsuno - Miyazaki, Japan",
    address: "Tsuno, Miyazaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.1697, longitude: 131.5672 },
  },
  {
    name: "Udo Jingu",
    location: "Nichinan - Miyazaki, Japan",
    address: "Nichinan, Miyazaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 31.6164, longitude: 131.4607 },
  },
  {
    name: "Mikado Shrine",
    location: "Miyazaki - Miyazaki, Japan",
    address: "Miyazaki Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 32.4873, longitude: 131.4206 },
  },

  // ─── KAGOSHIMA ───────────────────────────────────────────────────────────────
  {
    name: "Kirishima Shrine",
    location: "Kirishima - Kagoshima, Japan",
    address: "2608-5 Kirishima-Taguchi, Kirishima, Kagoshima Prefecture 899-4201, Japan",
    country: "Japan",
    coordinates: { latitude: 31.8589, longitude: 130.8719 },
  },
  {
    name: "Terukuni Shrine",
    location: "Kagoshima - Kagoshima, Japan",
    address: "Kagoshima, Kagoshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 31.5926, longitude: 130.5576 },
  },
  {
    name: "Kagoshima Shrine",
    location: "Kirishima - Kagoshima, Japan",
    address: "Kirishima, Kagoshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 31.9234, longitude: 130.8442 },
  },
  {
    name: "Nitta Shrine",
    location: "Satsumasendai - Kagoshima, Japan",
    address: "Satsumasendai, Kagoshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 31.8176, longitude: 130.302 },
  },
  {
    name: "Hirasaki Shrine",
    location: "Ibusuki - Kagoshima, Japan",
    address: "Ibusuki, Kagoshima Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 31.2462, longitude: 130.6373 },
  },

  // ─── OKINAWA ─────────────────────────────────────────────────────────────────
  {
    name: "Naminoue Shrine",
    location: "Naha - Okinawa, Japan",
    address: "Wakasa, Naha, Okinawa Prefecture, Japan",
    country: "Japan",
    coordinates: { latitude: 26.2206, longitude: 127.6714 },
  },
];

Shrine.deleteMany({})
  .then(() => Shrine.insertMany(shrines))
  .then((docs) => {
    console.log(`Seeded ${docs.length} shrines.`);
    process.exit(0);
  })
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
